Integrated ledger4j
Centrys/aion_ui pull request #12
Opened 2018-11-20 14:47 UTC by centrys-cristian-ilca

2018-11-20 15:06 UTC, centrys-otniel commented on src/main/java/org/aion/wallet/hardware/ledger/LedgerWallet.java
>      private static final int RETRIES = 3;
We should remove the retry mechanism as well. We used to do this because the JS calls would sometimes fail if called in quick succession

2018-11-20 15:06 UTC, centrys-otniel commented on src/main/java/org/aion/wallet/hardware/ledger/LedgerWallet.java
> +            ledgerDevice = LedgerUtilities.findLedgerDevice();
We can replace this with a call to `getAccountDetails(FIRST_INDEX);` which will remove the duplicated code and also ensure that we lock access to the Ledger resource

2018-11-20 15:06 UTC, centrys-otniel commented on src/main/java/org/aion/wallet/hardware/ledger/LedgerWallet.java
> +            LedgerDevice ledgerDevice = LedgerUtilities.findLedgerDevice();
We should lock this call as well

2018-11-20 15:06 UTC, centrys-otniel commented on src/main/java/org/aion/wallet/hardware/ledger/LedgerWallet.java
> +            ledgerDevice.close();
Call `ledgerDevice.close()` on a finally block

2018-11-20 16:25 UTC, theotniel requested changes
Also, ne need to remove the archives from `native/ledger`, update `build.xml` to exclude said archives and update `AionWalletLauncher`, `inno_setup.iss` to no longer install the portable node js and remove all related executables from `scripts`

2018-11-20 16:32 UTC, qoire commented
On the ledger4j library side: An updated is needed to support Mac and Windows functionality. I will test those today.

2018-11-20 16:32 UTC, qoire requested changes
Dependant on build script changes + library update

2018-11-21 18:09 UTC, qoire commented
I believe as of today, the ledger4j library can be considered functional and somewhat tested. We ironed out the bugs on all 3 platforms.

2018-11-21 18:20 UTC, theotniel approved these changes

2018-11-21 18:31 UTC, merged